name: Lint and Email

on:
  push:
    branches:
      - main  

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run lint_email.py
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          if ! flake8 lint_email.py; then
            echo "Linting failed. Exiting without pushing to main branch."
            exit 78
          else
            echo "Linting passed. Code is ready for push."
          fi

      - name: Push to main branch
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Linting successful"
          git push origin main
