name: Lint Check

on:
  push:
    branches:
      - main 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Notify on lint failure
        if: failure()
        run: |
          echo "Lint checks failed. Sending email notification."
          python3 lint_email.py
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
